
package br.com.i9virtual.imobby.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImobbyAutWS", targetNamespace = "http://ws.imobby.i9virtual.com.br/", wsdlLocation = "http://www.imobby.com.br:8080/ImobbyWS?WSDL")
public class ImobbyAutWS
    extends Service
{

    private final static URL IMOBBYAUTWS_WSDL_LOCATION;
    private final static WebServiceException IMOBBYAUTWS_EXCEPTION;
    private final static QName IMOBBYAUTWS_QNAME = new QName("http://ws.imobby.i9virtual.com.br/", "ImobbyAutWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.imobby.com.br:8080/ImobbyWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMOBBYAUTWS_WSDL_LOCATION = url;
        IMOBBYAUTWS_EXCEPTION = e;
    }

    public ImobbyAutWS() {
        super(__getWsdlLocation(), IMOBBYAUTWS_QNAME);
    }

    public ImobbyAutWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMOBBYAUTWS_QNAME, features);
    }

    public ImobbyAutWS(URL wsdlLocation) {
        super(wsdlLocation, IMOBBYAUTWS_QNAME);
    }

    public ImobbyAutWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMOBBYAUTWS_QNAME, features);
    }

    public ImobbyAutWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImobbyAutWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImobbyAut
     */
    @WebEndpoint(name = "ImobbyAutWSPort")
    public ImobbyAut getImobbyAutWSPort() {
        return super.getPort(new QName("http://ws.imobby.i9virtual.com.br/", "ImobbyAutWSPort"), ImobbyAut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImobbyAut
     */
    @WebEndpoint(name = "ImobbyAutWSPort")
    public ImobbyAut getImobbyAutWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.imobby.i9virtual.com.br/", "ImobbyAutWSPort"), ImobbyAut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMOBBYAUTWS_EXCEPTION!= null) {
            throw IMOBBYAUTWS_EXCEPTION;
        }
        return IMOBBYAUTWS_WSDL_LOCATION;
    }

}
